apiVersion: ranch/v1
kind: AgentTemplate
metadata:
  id: template-859968c4-fff8-4a3c-8c5d-55322c5aa77f
  name: Stable OpenCart 4 Frontend
  version: 0.0.0
  description: Stable module agent for convenient work of Opencart 4 customers in
    the frontend
files:
  agent: ./.agent
  paddock: ./.paddock
skills:
  - id: stable-opencart4-frontend
    source: ./.agent/skills/stable-opencart4-frontend
mcp: []
secrets: []
paddock:
  seedScenarios: true
