apiVersion: ranch/v1
kind: AgentTemplate
metadata:
  id: template-86df834d-5de1-4875-ba6e-da6e3fd5da66
  name: Stable OpenCart Backend
  version: 0.0.0
  description: Stable module agent for convenient work of Opencart users in the backend
files:
  agent: ./.agent
  paddock: ./.paddock
skills:
  - id: stable-opencart-backend
    source: ./.agent/skills/stable-opencart-backend
mcp: []
secrets: []
paddock:
  seedScenarios: true
