apiVersion: ranch/v1
kind: AgentTemplate
metadata:
  id: template-104ecfbf-1507-4345-a3d1-45e3a6a58aef
  name: Stable OpenCart 3 Frontend
  version: 0.0.0
  description: Stable module agent for convenient work of Opencart 3 customers in the frontend
files:
  agent: ./.agent
  paddock: ./.paddock
skills:
  - id: stable-opencart3-frontend
    source: ./.agent/skills/stable-opencart3-frontend
mcp: []
secrets: []
paddock:
  seedScenarios: true
