apiVersion: ranch/v1
kind: AgentTemplate
metadata:
  id: template-9e6c1421-be9c-4cc0-9758-d7365549299f
  name: Stable OpenCart Frontend
  version: 0.0.0
  description: Stable module agent for convenient work of Opencart customers in the frontend
files:
  agent: ./.agent
  paddock: ./.paddock
skills:
  - id: stable-opencart-frontend
    source: ./.agent/skills/stable-opencart-frontend
mcp: []
secrets: []
paddock:
  seedScenarios: true
